# Generated by Django 3.1.4 on 2022-08-18 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('allowance', models.IntegerField(blank=True, null=True, verbose_name='Allowance (if any)')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_part_time', models.BooleanField(default=False, verbose_name='Part Time')),
                ('num_vacancies', models.IntegerField(verbose_name='Number of vacancies')),
                ('notice_image', models.FileField(upload_to='jobs/notice-images', verbose_name='Announcement Notice')),
                ('announced_date', models.DateTimeField(default=datetime.datetime.now)),
                ('deadline_date', models.DateTimeField(verbose_name='Last Application Date')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
