# Generated by Django 3.1.4 on 2022-08-18 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
        ('jobs', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='vacancy', to='records.Applicant'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job', to='professional.category'),
        ),
        migrations.AddField(
            model_name='job',
            name='min_qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='professional.qualification', verbose_name='Minimum Required Qualification'),
        ),
        migrations.AddField(
            model_name='job',
            name='min_required_experience',
            field=models.ManyToManyField(related_name='job', to='professional.Experience', verbose_name='Minimum Required Experience'),
        ),
        migrations.AddField(
            model_name='job',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='records.provider'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(related_name='job', to='professional.Skill'),
        ),
    ]
